[package]
name = "civilization-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
netcdf-reader = "0.9.1"
rayon.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tiff.workspace = true
tokio.workspace = true
weezl.workspace = true
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
world-data = { path = "../../crates/world-data" }
world-data-filesystem = { path = "../../crates/world-data-filesystem" }
world-domain = { path = "../../crates/world-domain" }

[lints]
workspace = true
