[package]
name = "civilization-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
world-data = { path = "../../crates/world-data" }
world-data-filesystem = { path = "../../crates/world-data-filesystem" }
world-domain = { path = "../../crates/world-domain" }

[lints]
workspace = true
