const COMMON_SPECIES_NAMES: Readonly<Record<string, string>> = {
  "Aimophila ruficeps": "Rufous-crowned sparrow",
  "Antrozous pallidus": "Pallid bat",
  "Buteo jamaicensis": "Red-tailed hawk",
  "Callipepla californica": "California quail",
  "Callisaurus draconoides": "Zebra-tailed lizard",
  "Campylorhynchus brunneicapillus": "Cactus wren",
  "Charadrius vociferus": "Killdeer",
  "Colaptes chrysoides": "Gilded flicker",
  "Coleonyx variegatus": "Western banded gecko",
  "Corvus corax": "Common raven",
  "Egretta rufescens": "Reddish egret",
  "Homo sapiens": "Human",
  "Icterus cucullatus": "Hooded oriole",
  "Icterus parisorum": "Scott's oriole",
  "Lanius ludovicianus": "Loggerhead shrike",
  "Larus heermanni": "Heermann's gull",
  "Larus occidentalis": "Western gull",
  "Lepus californicus": "Black-tailed jackrabbit",
  "Mimus polyglottos": "Northern mockingbird",
  "Myotis californicus": "California myotis bat",
  "Numenius americanus": "Long-billed curlew",
  "Ovis canadensis": "Bighorn sheep",
  "Phainopepla nitens": "Phainopepla",
  "Pipilo chlorurus": "Green-tailed towhee",
  "Piranga ludoviciana": "Western tanager",
  "Salvadora hexalepis": "Western patch-nosed snake",
  "Sayornis saya": "Say's phoebe",
  "Setophaga coronata": "Yellow-rumped warbler",
  "Toxostoma cinereum": "Gray thrasher",
  "Urocyon cinereoargenteus": "Gray fox",
  "Urosaurus nigricauda": "Black-tailed brush lizard",
  "Zenaida macroura": "Mourning dove",
  "Zonotrichia leucophrys": "White-crowned sparrow",
};

export function commonSpeciesName(scientificName: string) {
  return COMMON_SPECIES_NAMES[scientificName] ?? scientificName;
}
