[package]
name = "observer-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
application = { path = "../application" }
observer-projection = { path = "../observer-projection" }
axum.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
stripe-adapter = { path = "../stripe-adapter" }
tower-http.workspace = true
tracing.workspace = true
world-domain = { path = "../world-domain" }

[lints]
workspace = true
