use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use crate::{CanonicalHashError, Digest, WorldId};

pub const CANCER_TISSUE_REFINEMENT_PROTOCOL_SCHEMA_VERSION: u16 = 1;
pub const CANCER_TISSUE_REFINEMENT_RESULT_SCHEMA_VERSION: u16 = 1;
pub const CANCER_TISSUE_REFINEMENT_METHOD_VERSION: u16 = 1;
pub const CANCER_TISSUE_REFINEMENT_SCENARIO_COUNT: usize = 3;
pub const CANCER_TISSUE_REFINEMENT_MIN_GRID_EDGE: u16 = 16;
pub const CANCER_TISSUE_REFINEMENT_MAX_GRID_EDGE: u16 = 32;
pub const CANCER_TISSUE_REFINEMENT_MAX_GRID_SITES: u32 = 1_024;
pub const CANCER_TISSUE_REFINEMENT_MAX_INITIAL_CELLS: u32 = 2_048;
pub const CANCER_TISSUE_REFINEMENT_MAX_CELLS: u32 = 4_096;
pub const CANCER_TISSUE_REFINEMENT_MAX_STEPS: u16 = 256;
pub const CANCER_TISSUE_REFINEMENT_MAX_SNAPSHOTS_PER_SCENARIO: usize = 16;
pub const CANCER_TISSUE_REFINEMENT_MAX_OUTPUT_SNAPSHOTS: usize =
    CANCER_TISSUE_REFINEMENT_SCENARIO_COUNT * CANCER_TISSUE_REFINEMENT_MAX_SNAPSHOTS_PER_SCENARIO;
pub const CANCER_TISSUE_REFINEMENT_CAVEATS: [&str; 4] = [
    "This is an uncalibrated deterministic tissue projection, not biological, animal, clinical, safety, or efficacy evidence.",
    "Cells are bounded population units on a two-dimensional lattice; they are not an exact tumor, organoid, mouse, or person.",
    "Oxygen, nutrient, exposure, clone behavior, and device fields are structural proxies with fixed-point coefficients, not measured intervention parameters.",
    "The uncertainty envelope varies only the preregistered field bound and does not quantify total biological or clinical uncertainty.",
];

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CancerTissueRefinementFieldModel {
    DiffusiveExposure,
    DeviceField,
    ResectionMask,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CancerTissueRefinementScenario {
    LowerFieldBound,
    NominalAssumptions,
    UpperFieldBound,
}

impl CancerTissueRefinementScenario {
    pub const ALL: [Self; CANCER_TISSUE_REFINEMENT_SCENARIO_COUNT] = [
        Self::LowerFieldBound,
        Self::NominalAssumptions,
        Self::UpperFieldBound,
    ];
}

/// Frozen input to the bounded tissue engine. Numeric choices are generated by
/// the method implementation from prior immutable results; they are never filled
/// in by a language model.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CancerTissueRefinementProtocol {
    pub schema_version: u16,
    pub method_version: u16,
    pub refinement_id: Uuid,
    pub world_id: WorldId,
    pub campaign_id: Uuid,
    pub root_request_id: Uuid,
    pub root_artifact_hash: Digest,
    pub root_plan_hash: Digest,
    pub root_result_hash: Digest,
    pub survival_synthesis_request_id: Uuid,
    pub survival_synthesis_request_hash: Digest,
    pub survival_synthesis_result_hash: Digest,
    pub campaign_result_hashes: Vec<Digest>,
    pub field_model: CancerTissueRefinementFieldModel,
    pub lattice_width: u16,
    pub lattice_height: u16,
    pub initial_cell_count: u32,
    pub cell_capacity: u32,
    pub maximum_steps: u16,
    pub snapshot_every_steps: u16,
    pub requested_exposure_hours: u16,
    pub modeled_exposure_hours: u16,
    pub horizon_truncated: bool,
    pub scenarios: Vec<CancerTissueRefinementScenario>,
}

impl CancerTissueRefinementProtocol {
    #[must_use]
    pub fn deterministic_id(campaign_id: Uuid, method_version: u16) -> Uuid {
        Uuid::new_v5(
            &campaign_id,
            format!("observer-tissue-refinement:v{method_version}").as_bytes(),
        )
    }

    pub fn validate(&self) -> Result<(), CancerTissueRefinementContractError> {
        let sites = u32::from(self.lattice_width) * u32::from(self.lattice_height);
        let maximum_snapshots = usize::from(
            self.maximum_steps
                .div_ceil(self.snapshot_every_steps.max(1)),
        );
        if self.schema_version != CANCER_TISSUE_REFINEMENT_PROTOCOL_SCHEMA_VERSION
            || self.method_version != CANCER_TISSUE_REFINEMENT_METHOD_VERSION
            || self.refinement_id != Self::deterministic_id(self.campaign_id, self.method_version)
            || self.campaign_id.is_nil()
            || self.root_request_id.is_nil()
            || self.root_artifact_hash == Digest::ZERO
            || self.root_plan_hash == Digest::ZERO
            || self.root_result_hash == Digest::ZERO
            || self.survival_synthesis_request_id.is_nil()
            || self.survival_synthesis_request_hash == Digest::ZERO
            || self.survival_synthesis_result_hash == Digest::ZERO
            || !(3..=5).contains(&self.campaign_result_hashes.len())
            || self
                .campaign_result_hashes
                .windows(2)
                .any(|pair| pair[0] >= pair[1])
            || self.campaign_result_hashes.contains(&Digest::ZERO)
            || !(CANCER_TISSUE_REFINEMENT_MIN_GRID_EDGE..=CANCER_TISSUE_REFINEMENT_MAX_GRID_EDGE)
                .contains(&self.lattice_width)
            || !(CANCER_TISSUE_REFINEMENT_MIN_GRID_EDGE..=CANCER_TISSUE_REFINEMENT_MAX_GRID_EDGE)
                .contains(&self.lattice_height)
            || sites > CANCER_TISSUE_REFINEMENT_MAX_GRID_SITES
            || self.initial_cell_count == 0
            || self.initial_cell_count > CANCER_TISSUE_REFINEMENT_MAX_INITIAL_CELLS
            || self.cell_capacity < self.initial_cell_count
            || self.cell_capacity > CANCER_TISSUE_REFINEMENT_MAX_CELLS
            || self.maximum_steps == 0
            || self.maximum_steps > CANCER_TISSUE_REFINEMENT_MAX_STEPS
            || self.snapshot_every_steps == 0
            || maximum_snapshots > CANCER_TISSUE_REFINEMENT_MAX_SNAPSHOTS_PER_SCENARIO
            || self.requested_exposure_hours == 0
            || self.modeled_exposure_hours == 0
            || self.modeled_exposure_hours > self.requested_exposure_hours
            || self.horizon_truncated
                != (self.modeled_exposure_hours < self.requested_exposure_hours)
            || self.scenarios.as_slice() != CancerTissueRefinementScenario::ALL
        {
            return Err(CancerTissueRefinementContractError::InvalidProtocol);
        }
        Ok(())
    }

    pub fn canonical_hash(&self) -> Result<Digest, CancerTissueRefinementContractError> {
        self.validate()?;
        Ok(Digest::canonical(self)?)
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CancerTissueRefinementTermination {
    CompletedBoundedHorizon,
    CellCapacityReached,
    NumericalInvariantRejected,
}

/// One compact checkpoint. Per-cell trajectories are deliberately excluded
/// from the durable result; the frozen protocol and method reproduce them.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CancerTissueRefinementSnapshot {
    pub scenario: CancerTissueRefinementScenario,
    pub step: u16,
    pub viable_cells: u32,
    pub treatment_sensitive_cells: u32,
    pub drug_tolerant_cells: u32,
    pub resistant_cells: u32,
    pub mean_oxygen_parts_per_million: u32,
    pub mean_nutrient_parts_per_million: u32,
    pub mean_intervention_field_parts_per_million: u32,
    pub hypoxic_cell_fraction_parts_per_million: u32,
    pub invasive_front_fraction_parts_per_million: u32,
}

impl CancerTissueRefinementSnapshot {
    fn validate(&self, protocol: &CancerTissueRefinementProtocol) -> bool {
        let clone_total = u64::from(self.treatment_sensitive_cells)
            + u64::from(self.drug_tolerant_cells)
            + u64::from(self.resistant_cells);
        self.step <= protocol.maximum_steps
            && self.viable_cells <= protocol.cell_capacity
            && clone_total == u64::from(self.viable_cells)
            && self.mean_oxygen_parts_per_million <= 1_000_000
            && self.mean_nutrient_parts_per_million <= 1_000_000
            && self.mean_intervention_field_parts_per_million <= 1_000_000
            && self.hypoxic_cell_fraction_parts_per_million <= 1_000_000
            && self.invasive_front_fraction_parts_per_million <= 1_000_000
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CancerTissueRefinementScenarioSummary {
    pub scenario: CancerTissueRefinementScenario,
    pub termination: CancerTissueRefinementTermination,
    pub completed_steps: u16,
    pub initial_viable_cells: u32,
    pub final_viable_cells: u32,
    pub final_treatment_sensitive_cells: u32,
    pub final_drug_tolerant_cells: u32,
    pub final_resistant_cells: u32,
    pub final_mean_oxygen_parts_per_million: u32,
    pub final_mean_nutrient_parts_per_million: u32,
    pub final_mean_intervention_field_parts_per_million: u32,
    pub final_hypoxic_cell_fraction_parts_per_million: u32,
    pub final_invasive_front_fraction_parts_per_million: u32,
    pub lattice_site_updates: u64,
}

impl CancerTissueRefinementScenarioSummary {
    fn validate(&self, protocol: &CancerTissueRefinementProtocol) -> bool {
        let clone_total = u64::from(self.final_treatment_sensitive_cells)
            + u64::from(self.final_drug_tolerant_cells)
            + u64::from(self.final_resistant_cells);
        let maximum_site_updates = u64::from(protocol.lattice_width)
            * u64::from(protocol.lattice_height)
            * u64::from(protocol.maximum_steps);
        self.completed_steps <= protocol.maximum_steps
            && (self.termination != CancerTissueRefinementTermination::CompletedBoundedHorizon
                || self.completed_steps == protocol.maximum_steps)
            && self.initial_viable_cells == protocol.initial_cell_count
            && self.final_viable_cells <= protocol.cell_capacity
            && clone_total == u64::from(self.final_viable_cells)
            && self.final_mean_oxygen_parts_per_million <= 1_000_000
            && self.final_mean_nutrient_parts_per_million <= 1_000_000
            && self.final_mean_intervention_field_parts_per_million <= 1_000_000
            && self.final_hypoxic_cell_fraction_parts_per_million <= 1_000_000
            && self.final_invasive_front_fraction_parts_per_million <= 1_000_000
            && self.lattice_site_updates <= maximum_site_updates
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CancerTissueRefinementUncertaintyEnvelope {
    pub minimum_final_viable_cells: u32,
    pub maximum_final_viable_cells: u32,
    pub final_viable_spread_parts_per_million_of_initial: u32,
    pub all_scenarios_completed: bool,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CancerTissueRefinementResult {
    pub schema_version: u16,
    pub method_version: u16,
    pub refinement_id: Uuid,
    pub world_id: WorldId,
    pub protocol_hash: Digest,
    pub scenario_summaries: Vec<CancerTissueRefinementScenarioSummary>,
    pub snapshots: Vec<CancerTissueRefinementSnapshot>,
    pub uncertainty: CancerTissueRefinementUncertaintyEnvelope,
    pub evidence_class: String,
    pub caveats: Vec<String>,
}

impl CancerTissueRefinementResult {
    pub fn validate_against(
        &self,
        protocol: &CancerTissueRefinementProtocol,
    ) -> Result<(), CancerTissueRefinementContractError> {
        protocol.validate()?;
        let scenario_order = self
            .scenario_summaries
            .iter()
            .map(|summary| summary.scenario)
            .collect::<Vec<_>>();
        let minimum = self
            .scenario_summaries
            .iter()
            .map(|summary| summary.final_viable_cells)
            .min()
            .unwrap_or_default();
        let maximum = self
            .scenario_summaries
            .iter()
            .map(|summary| summary.final_viable_cells)
            .max()
            .unwrap_or_default();
        let spread =
            maximum.saturating_sub(minimum).saturating_mul(1_000_000) / protocol.initial_cell_count;
        let all_completed = self.scenario_summaries.iter().all(|summary| {
            summary.termination == CancerTissueRefinementTermination::CompletedBoundedHorizon
        });
        let snapshot_order_valid = self.snapshots.windows(2).all(|pair| {
            pair[0].scenario < pair[1].scenario
                || (pair[0].scenario == pair[1].scenario && pair[0].step < pair[1].step)
        });
        let snapshot_counts_valid = CancerTissueRefinementScenario::ALL.iter().all(|scenario| {
            let snapshots = self
                .snapshots
                .iter()
                .filter(|snapshot| snapshot.scenario == *scenario)
                .collect::<Vec<_>>();
            let summary = self
                .scenario_summaries
                .iter()
                .find(|summary| summary.scenario == *scenario);
            !snapshots.is_empty()
                && snapshots.len() <= CANCER_TISSUE_REFINEMENT_MAX_SNAPSHOTS_PER_SCENARIO
                && summary.is_some_and(|summary| {
                    snapshots_are_complete(protocol, summary, &snapshots)
                        && snapshots
                            .last()
                            .is_some_and(|snapshot| snapshot_matches_summary(snapshot, summary))
                })
        });
        if self.schema_version != CANCER_TISSUE_REFINEMENT_RESULT_SCHEMA_VERSION
            || self.method_version != protocol.method_version
            || self.refinement_id != protocol.refinement_id
            || self.world_id != protocol.world_id
            || self.protocol_hash != protocol.canonical_hash()?
            || scenario_order.as_slice() != CancerTissueRefinementScenario::ALL
            || self
                .scenario_summaries
                .iter()
                .any(|summary| !summary.validate(protocol))
            || self.snapshots.is_empty()
            || self.snapshots.len() > CANCER_TISSUE_REFINEMENT_MAX_OUTPUT_SNAPSHOTS
            || !snapshot_order_valid
            || !snapshot_counts_valid
            || self
                .snapshots
                .iter()
                .any(|snapshot| !snapshot.validate(protocol))
            || self.uncertainty.minimum_final_viable_cells != minimum
            || self.uncertainty.maximum_final_viable_cells != maximum
            || self
                .uncertainty
                .final_viable_spread_parts_per_million_of_initial
                != spread
            || self.uncertainty.all_scenarios_completed != all_completed
            || self.evidence_class != "uncalibrated_deterministic_tissue_projection"
            || self.caveats
                != CANCER_TISSUE_REFINEMENT_CAVEATS
                    .iter()
                    .map(|caveat| (*caveat).to_owned())
                    .collect::<Vec<_>>()
        {
            return Err(CancerTissueRefinementContractError::InvalidResult);
        }
        Ok(())
    }

    pub fn canonical_hash(
        &self,
        protocol: &CancerTissueRefinementProtocol,
    ) -> Result<Digest, CancerTissueRefinementContractError> {
        self.validate_against(protocol)?;
        Ok(Digest::canonical(self)?)
    }
}

fn snapshots_are_complete(
    protocol: &CancerTissueRefinementProtocol,
    summary: &CancerTissueRefinementScenarioSummary,
    snapshots: &[&CancerTissueRefinementSnapshot],
) -> bool {
    let mut expected_steps = (protocol.snapshot_every_steps..=summary.completed_steps)
        .step_by(usize::from(protocol.snapshot_every_steps))
        .collect::<Vec<_>>();
    if expected_steps.last().copied() != Some(summary.completed_steps) {
        expected_steps.push(summary.completed_steps);
    }
    snapshots
        .iter()
        .map(|snapshot| snapshot.step)
        .eq(expected_steps)
}

fn snapshot_matches_summary(
    snapshot: &CancerTissueRefinementSnapshot,
    summary: &CancerTissueRefinementScenarioSummary,
) -> bool {
    snapshot.step == summary.completed_steps
        && snapshot.viable_cells == summary.final_viable_cells
        && snapshot.treatment_sensitive_cells == summary.final_treatment_sensitive_cells
        && snapshot.drug_tolerant_cells == summary.final_drug_tolerant_cells
        && snapshot.resistant_cells == summary.final_resistant_cells
        && snapshot.mean_oxygen_parts_per_million == summary.final_mean_oxygen_parts_per_million
        && snapshot.mean_nutrient_parts_per_million == summary.final_mean_nutrient_parts_per_million
        && snapshot.mean_intervention_field_parts_per_million
            == summary.final_mean_intervention_field_parts_per_million
        && snapshot.hypoxic_cell_fraction_parts_per_million
            == summary.final_hypoxic_cell_fraction_parts_per_million
        && snapshot.invasive_front_fraction_parts_per_million
            == summary.final_invasive_front_fraction_parts_per_million
}

#[derive(Debug, Error)]
pub enum CancerTissueRefinementContractError {
    #[error("the tissue-refinement protocol is invalid or exceeds its resource envelope")]
    InvalidProtocol,
    #[error("the tissue-refinement result is invalid")]
    InvalidResult,
    #[error(transparent)]
    CanonicalHash(#[from] CanonicalHashError),
}
