[package]
name = "postgres-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
application = { path = "../application" }
observer-projection = { path = "../observer-projection" }
observer-auth = { path = "../observer-auth" }
async-trait.workspace = true
chrono.workspace = true
flate2.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
sim-engine = { path = "../sim-engine" }
sqlx.workspace = true
stripe-adapter = { path = "../stripe-adapter" }
uuid.workspace = true
url.workspace = true
world-domain = { path = "../world-domain" }

[dev-dependencies]
anyhow.workspace = true
tokio.workspace = true

[lints]
workspace = true
