[package]
name = "application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sim-engine = { path = "../sim-engine" }
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
world-domain = { path = "../world-domain" }

[lints]
workspace = true

[dev-dependencies]
tokio.workspace = true
