[package]
name = "civilization-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
dotenvy.workspace = true
observer-api = { path = "../../crates/observer-api" }
postgres-store = { path = "../../crates/postgres-store" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
